apiVersion: v1
kind: Secret
metadata:
  name: database-endpoint
type: Opaque
stringData:
  url: "YUGABYTEDB_URL"
  user: "YUGABYTEDB_USERNAME"
  password: "YUGABYTEDB_PASSWORD"
  #YugabyteDB deployment type - standard, replica or geo
  type: "standard"
  # database schema
  # `classpath:messenger_schema.sql` or `classpath:messenger_schema_partitioned.sql`
  schema: "classpath:messenger_schema.sql"
