apiVersion: v1
kind: Service
metadata:
  name: messenger-service
  namespace: geo-messenger
  labels:
    app: messenger
spec:
  type: LoadBalancer
  selector:
    app: messenger
  ports:
    - port: 80
      targetPort: 80
