apiVersion: v1
kind: Service
metadata:
  name: attachments-service
  namespace: geo-messenger
  labels:
    app: attachments
spec:
  type: ClusterIP
  selector:
    app: attachments
  ports:
    - port: 80
      targetPort: 80
